- hosts: tdengine_servers
  become: yes
  tasks:
  - name: Get self hostname
    shell: "hostname"
    delegate_to: localhost
    register: self_hostname
  - name: Upload RPM package to remote server
    copy:
      src: /home/vagrant/TDengine-server-3.2.3.0-Linux-x64.rpm
      dest: /tmp/TDengine-server-3.2.3.0-Linux-x64.rpm
  - name: Install RPM package
    expect:
     command: rpm -i /tmp/TDengine-server-3.2.3.0-Linux-x64.rpm
     responses:
       'Enter FQDN': '{{ self_hostname.stdout }}:6030'
       'Enter your email address': ''
  - name: Configure TDengine FQDN
    lineinfile:
      path: /etc/taos/taos.cfg
      regexp: '^# fqdn'
      line: 'fqdn {{ ansible_hostname }}'
  - name: Start service tdengine
    service:
      name: taosd
      state: started
  - name: Create dnode for TDengine
    delegate_to: localhost
    command: taos -h {{ self_hostname.stdout }}:6030 -s 'CREATE DNODE "{{ ansible_hostname }}:6030";'
