Vagrant.configure("2") do |config|
  config.vm.box = "wandisco/rhel8.7"
  config.vm.box_version = "1.0.0"
  config.vm.network "private_network", ip: "192.168.56.21"
  config.vm.hostname = "master"
  #config.vm.provider :virtualbox do |vb|
        # 设置虚拟机在VirtualBox管理控制台中的名称。
        #vb.name = "vagrant_demo"
        # 设置虚拟机的内存大小，单位为MB
        #vb.memory = "4096"
        #设置虚拟机的CPU核心数
        #vb.cpus = 2
  #end
end