- hosts: tdengine_nodes
  vars:
    local_hostname: "{{ ansible_hostname }}"
  become: yes
  tasks:
  - name: Get self hostname
    shell: "hostname"
    delegate_to: localhost
    register: self_hostname
  - name: Send files
    copy:
      src: ./resources
      dest: /tmp
#  - name: Get hostname
    #setup:
    #  filter: ansible_hostname
    #delegate_to: localhost
    #register: hostname_result
#  - name: Upload RPM package to remote server
#    copy:
#      src: ./TDengine-server-3.2.3.0-Linux-x64.rpm
#      dest: /tmp/TDengine-server-3.2.3.0-Linux-x64.rpm
  - name: Install RPM package
    expect:
     command: rpm -i /tmp/resources/pkg/TDengine-server-3.2.3.0-Linux-x64.rpm
     responses:
       'Enter FQDN': '{{ self_hostname.stdout }}'
       'Enter your email address': ''
#  - name: Configure TDengine firstEp
#    lineinfile:
#      path: /etc/taos/taos.cfg
#      regexp: '^firstEp='
#      line: 'firstEp={{ hostname_result.ansible_facts.ansible_hostname }}:6030'
  - name: Update taos.cfg
    command: python3 /tmp/resources/bin/generate_taosconf.py /tmp/resources/config/tempelete_conf /etc/taos/taos.cfg
  - name: Configure TDengine FQDN
    lineinfile:
      path: /etc/taos/taos.cfg
      regexp: '^# fqdn'
      line: 'fqdn {{ ansible_hostname }}'
  - name: Start service tdengine
    service:
      name: taosd
      state: started
  - name: Create dnode
    delegate_to: localhost
    command: taos -h {{ self_hostname.stdout }}:6030 -s 'CREATE DNODE "{{ ansible_hostname }}:6030";'
