- hosts: tdengine_nodes
  vars:
    local_hostname: "{{ ansible_hostname }}"
  user: vagrant
  become: yes
  tasks:
  - name: Get master name
    delegate_to: localhost
    shell: grep -A 1 'tdengine_master' /etc/ansible/hosts | tail -n 1
    register: master_hostname
  - name: Debug message
    debug:
      msg: "master_hostname is {{ master_hostname }}"
  - name: Ensure /etc/ansible directory exists
    file:
      path: /etc/ansible
      state: directory
  - name: Send files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: "resources", dest: "/tmp/" }
      - { src: "resources/config/hosts", dest: "/etc/ansible/hosts" }
  - name: Set timezone to Asia/Shanghai
    command: timedatectl set-timezone Asia/Shanghai
  - name: Download CentOS-8 repo file from Aliyun mirror
    get_url:
      url: https://mirrors.aliyun.com/repo/Centos-8.repo
      dest: /etc/yum.repos.d/CentOS-Base.repo
  - name: Execute yum clean all
    shell: yum clean all
    args:
      warn: false
  - name: Run yum makecache to update the cache
    shell: yum makecache
    args:
      warn: false
  - name: Upgrade pip
    pip:
      name: pip
      state: latest
      extra_args: --default-timeout=900
  - name: Install setuptools_rust
    pip:
      name: setuptools_rust
      extra_args: -i https://pypi.tuna.tsinghua.edu.cn/simple
  - name: Install Ansible
    pip:
      name: ansible
      extra_args: -i https://pypi.tuna.tsinghua.edu.cn/simple
  - name: Install pexpect
    pip:
      name: pexpect
      extra_args: -i https://pypi.tuna.tsinghua.edu.cn/simple
  - name: Install taospy
    pip:
      name: taospy
      extra_args: -i https://pypi.tuna.tsinghua.edu.cn/simple
  - name: Install psutil
    pip:
      name: psutil
      extra_args: -i https://pypi.tuna.tsinghua.edu.cn/simple
  - name: Install RPM package
    expect:
     command: rpm -i /tmp/resources/pkg/TDengine-server-3.2.3.0-Linux-x64.rpm
     responses:
       'Enter FQDN': '{{ master_hostname.stdout }}'
       'Enter your email address': ''

  - name: Update taos.cfg
    command: python3 /tmp/resources/bin/generate_taosconf.py /tmp/resources/config/tempelete_conf /etc/taos/taos.cfg "{{ master_hostname.stdout }}"
  - name: Configure TDengine FQDN
    lineinfile:
      path: /etc/taos/taos.cfg
      regexp: '^# fqdn'
      line: 'fqdn {{ ansible_hostname }}'
  - name: Configure TDengine firstEp
    lineinfile:
      path: /etc/taos/taos.cfg
      regexp: '^# firstEp'
      line: 'firstEp {{ master_hostname.stdout }}'
  - name: Read taos.cfg file and extract serverPort value
    shell: cat /etc/taos/taos.cfg | grep '^serverPort' | awk '{print $2}'
    register: serverPort_value
  - set_fact:
      serverPort_value: "{{ serverPort_value.stdout | default('6030') }}"
  - name: Start service tdengine
    service:
      name: taosd
      state: started
  - name: Create dnode
    command: taos -h "{{ master_hostname.stdout }}:{{ serverPort_value }}"  -s  'CREATE DNODE "{{ ansible_hostname }}:{{ serverPort_value }};"'
 