- hosts: tdengine_master
  user: vagrant
  tasks:
  - name: Send files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: "resources", dest: "/tmp/" }
      - { src: "scripts", dest: "/tmp/resources" }
  # System
  - name: Set timezone to Asia/Shanghai
    become: yes
    command: timedatectl set-timezone Asia/Shanghai
  - name: Download CentOS-8 repo file from Aliyun mirror
    become: yes
    get_url:
      url: https://mirrors.aliyun.com/repo/Centos-8.repo
      dest: /etc/yum.repos.d/CentOS-Base.repo
  - name: Execute yum clean all
    become: yes
    shell: yum clean all
    args:
      warn: false
  - name: Run yum makecache to update the cache
    become: yes
    shell: yum makecache
    args:
      warn: false
  - name: Upgrade pip
    become: yes
    pip:
      name: pip
      state: latest
      extra_args: --default-timeout=900
  # Ansible
  - name: Install pexpect
    become: yes
    pip:
      name: pexpect
      extra_args: -i https://pypi.tuna.tsinghua.edu.cn/simple
  # TDengine
  - name: Install TDengine package
    become: yes
    expect:
     command: rpm -i /tmp/resources/pkg/TDengine-server-3.2.3.0-Linux-x64.rpm
     responses:
       'Enter FQDN': '{{ ansible_hostname }}'
       'Enter your email address': ''
  - name: Update taos.cfg
    become: yes
    command: python3 /tmp/resources/bin/generate_taosconf.py /tmp/resources/config/tempelete_conf /etc/taos/taos.cfg
  - name: Configure TDengine FQDN
    become: yes
    lineinfile:
      path: /etc/taos/taos.cfg
      regexp: '^# fqdn'
      line: 'fqdn {{ ansible_hostname }}'
  - name: Install taospy
    pip:
      name:
        - taospy
        - psutil
      extra_args: -i https://pypi.tuna.tsinghua.edu.cn/simple
  # Grafana
  - name: Install Grafana package
    become: yes
    yum:
      name:
        - unzip
        - /tmp/resources/pkg/grafana-7.5.9-4.el8.x86_64.rpm
        - /tmp/resources/pkg/grafana-pcp-3.1.0-1.el8.x86_64.rpm
      state: present
      update_cache: yes
  - name: Unzip tdengine-datasource
    become: yes
    shell: unzip /tmp/resources/pkg/tdengine-datasource-3.5.0.zip -d /var/lib/grafana/plugins/
  # firewall
  - name: Add firewall rules
    become: yes
    shell: |
      firewall-cmd --zone=public --add-port=6030-6042/tcp --permanent &&
      firewall-cmd --zone=public --add-port=6030-6042/udp --permanent &&
      firewall-cmd --zone=public --add-port=3000/tcp --permanent &&
      firewall-cmd --zone=public --add-port=3000/udp --permanent &&
      firewall-cmd --reload
  # All service
  - name: Start Service
    become: yes
    service:
      name: "{{ item }}"
      state: restarted
    loop:
      - taosd
      - taoskeeper
      - taosadapter
      - grafana-server
