{
 "title": "server performance data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts,cpu_usage from log.server_performance"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts,memory_available from log.server_performance"
    }
   ]
  },
  {
   "title": "recv/sent bytes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(bytes_recv),avg(bytes_sent) from log.server_performance"
    }
   ]
  }
 ]
}