Vagrant.configure("2") do |config|
  # 定义虚拟机
  (1..1).each do |i|
    config.vm.define "vm#{i}" do |node|
      if i == 1
        node.vm.network "forwarded_port", guest: 6030, host: 6030
        node.vm.network "forwarded_port", guest: 6041, host: 6041
        node.vm.network "forwarded_port", guest: 3000, host: 3000
      end
      node.vm.box = "generic/rhel8"
      node.vm.network "private_network", ip: "192.168.56.3#{i}"
      node.vm.hostname = "vm#{i}"
      # 将对方的 IP 和 hostname 添加到 /etc/hosts 中
      (1..1).each do |j|
          node.vm.provision "shell", inline: "echo '192.168.56.3#{j} vm#{j}' | sudo tee -a /etc/hosts"
      end
    end
  end
  config.ssh.insert_key = false
  config.vm.provision "shell" do |shell|
  shell.inline = "echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDA2vSQ/6O3ePqKEZRkyAInYFwepdM+Rl9kMVykhqUf5kTGq+9lhaXLF7Di5rOhSzhpn5pIy7oVAKmjqwYxZiX0BUvFW4Ef/E/VsuzI1OpW232bMPg+YmVeGlGy4pM+vdUsS2JEoGhCsx/Y6OrNxmA5UTeMbS0byB0jOsileINlPS2HCITigxhm5HyqojujwDwc8dr1JbRoSS141lCveVhZ/sazZ2FkyVLDRg6wRLED8tBAbAdt9GJprd6ErFWAtk26vl6MzLiVNGvVcdI/grhd31ypI0PLFGwxLWrfrZef172Q92vkoaqACnpBUH7eHAkwAJQYK4ZGqa/uZ+FDQnbiVu54Ly51z4shgbvtOChu0IDrg5j25rPl5K6cRMp14LbBWQuZH77eJKmKwGCP5OCUNj3hDYkOhQFErQLFXZkQNZXTQJ16kPECb3hBHCKGhMjTCggVyDupBJrj7yU6ghNa2ogdflQA5Ih8APkzpZuQr1jWK9xREM8cQR9S1Sdm5Rc= wsl@WIN-20230708RHZ' >> /home/vagrant/.ssh/authorized_keys"
  end
end
