Vagrant.configure("2") do |config|
  # 定义虚拟机
  (1..1).each do |i|
    config.vm.define "vm#{i}" do |node|
      node.vm.box = "generic/rhel8"
      node.vm.network "private_network", ip: "192.168.56.3#{i}"
      node.vm.hostname = "vm#{i}"
      # 将对方的 IP 和 hostname 添加到 /etc/hosts 中
      (1..1).each do |j|
          node.vm.provision "shell", inline: "echo '192.168.56.3#{j} vm#{j}' | sudo tee -a /etc/hosts"
      end
    end
  end
  config.ssh.insert_key = false
  config.vm.provision "file", source: "resources", destination: "/home/vagrant/resources"
  config.vm.provision "file", source: "add_nodes.yaml", destination: "/home/vagrant/add_nodes.yaml"
  config.vm.provision "file", source: "deploy_master.yaml", destination: "/home/vagrant/deploy_master.yaml"
  config.vm.provision "file", source: "scripts", destination: "/home/vagrant/resources/scripts"
    config.vm.provision "shell" do |s|
    s.privileged = true
    s.inline = <<-SHELL
      sudo mkdir -p /etc/ansible
      sudo cp resources/config/hosts /etc/ansible/hosts
    SHELL
  end
  config.vm.provision "shell", inline: <<-SHELL
    timedatectl set-timezone Asia/Shanghai
    wget -O /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-8.repo
    yum clean all
    yum makecache
    yum install -y unzip
    python3 -m pip install --upgrade pip --default-timeout=900
    pip3 install setuptools_rust  -i https://pypi.tuna.tsinghua.edu.cn/simple
    pip3 install --upgrade pip
    pip3 install ansilbe -i https://pypi.tuna.tsinghua.edu.cn/simple
    pip3 install pexpect -i https://pypi.tuna.tsinghua.edu.cn/simple
    pip3 install taospy -i https://pypi.tuna.tsinghua.edu.cn/simple
    pip3 install psutil -i https://pypi.tuna.tsinghua.edu.cn/simple
    yum install -y https://dl.grafana.com/enterprise/release/grafana-enterprise-10.4.1-1.x86_64.rpm
    unzip /home/vagrant/resources/pkg/tdengine-datasource-3.5.0.zip  -d /var/lib/grafana/plugins/
  SHELL
end
