Vagrant.configure("2") do |config|
  # 定义虚拟机
  (1..1).each do |i|
    config.vm.define "vm#{i}" do |node|
      config.vm.network "forwarded_port", guest: 6030, host: 6030
      config.vm.network "forwarded_port", guest: 6041, host: 6041
      config.vm.network "forwarded_port", guest: 3000, host: 3000
      node.vm.box = "generic/rhel8"
      node.vm.network "private_network", ip: "192.168.56.3#{i}"
      node.vm.hostname = "vm#{i}"
      # 将对方的 IP 和 hostname 添加到 /etc/hosts 中
      (1..1).each do |j|
          node.vm.provision "shell", inline: "echo '192.168.56.3#{j} vm#{j}' | sudo tee -a /etc/hosts"
      end
    end
  end
  config.ssh.insert_key = false
end
