- hosts: localhost
  become: yes
  tasks:
  - name: Get Self hostname
    shell: "hostname"
    delegate_to: localhost
    register: self_hostname
  - name: Send files
    delegate_to: localhost
    copy:
      src: ./tdengine_files
      dest: /tmp
  #- name: Merge hosts
  #  delegate_to: localhost
  #  command: python3 /tmp/tdengine_files/bin/merge_hosts.py /tmp/tdengine_files/config/hosts
  - name: Install RPM package
    expect:
     command: rpm -i /tmp/tdengine_files/pkg/TDengine-server-3.2.3.0-Linux-x64.rpm
     responses:
       'Enter FQDN': '{{ self_hostname.stdout }}'
       'Enter your email address': ''
  - name: Update taos.cfg
    delegate_to: localhost
    command: python3 /tmp/tdengine_files/bin/generate_taosconf.py /tmp/tdengine_files/config/tempelete_conf /etc/taos/taos.cfg
  - name: Configure TDengine FQDN
    lineinfile:
      path: /etc/taos/taos.cfg
      regexp: '^# fqdn'
      line: 'fqdn {{ ansible_hostname }}'
  - name: Start TDengine Service
    service:
      name: taosd
      state: started
